name: Unit Tests (monolithic)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    uses: RedHatInsights/processing-tools/.github/workflows/pytests.yaml@master
    secrets: inherit
    with:
      python_version: '3.14'
      requirements_file: monolithic/requirements-test.txt
      packages: monolithic
      coverage: true
